services:
  db:
    image: postgres:15
    volumes:
      - fgs_db:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
    restart: "on-failure"
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  test-db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: "testpassword"
      POSTGRES_USER: "testuser"
      POSTGRES_DB: "testdb"
    ports:
      - "5433:5432"
    env_file:
      - ./email_worker/.env.test
    tmpfs:
      - /var/lib/postgresql/data # Runs in RAM for speed!
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  fgs_db:
